In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest, f_regression
import csv
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

In [2]:
trainx_csv=pd.read_csv('/content/drive/MyDrive/MFG10YearTerminationData.csv')
null_values=trainx_csv.isnull()
missing_values=trainx_csv==" "
null_values=null_values.sum()
missing_values=missing_values.sum()
trainx_csv

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,job_title,store_name,gender_short,gender_full,termreason_desc,termtype_desc,STATUS_YEAR,STATUS,BUSINESS_UNIT
0,1318,12/31/2006 0:00,1/3/1954,8/28/1989,1/1/1900,52,17,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2006,ACTIVE,HEADOFFICE
1,1318,12/31/2007 0:00,1/3/1954,8/28/1989,1/1/1900,53,18,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2007,ACTIVE,HEADOFFICE
2,1318,12/31/2008 0:00,1/3/1954,8/28/1989,1/1/1900,54,19,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2008,ACTIVE,HEADOFFICE
3,1318,12/31/2009 0:00,1/3/1954,8/28/1989,1/1/1900,55,20,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2009,ACTIVE,HEADOFFICE
4,1318,12/31/2010 0:00,1/3/1954,8/28/1989,1/1/1900,56,21,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2010,ACTIVE,HEADOFFICE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49648,8258,12/1/2015 0:00,5/28/1994,8/19/2013,12/30/2015,21,2,Valemount,Dairy,Dairy Person,34,M,Male,Layoff,Involuntary,2015,TERMINATED,STORES
49649,8264,8/1/2013 0:00,6/13/1994,8/27/2013,8/30/2013,19,0,Vancouver,Customer Service,Cashier,44,F,Female,Resignaton,Voluntary,2013,TERMINATED,STORES
49650,8279,12/1/2015 0:00,7/18/1994,9/15/2013,12/30/2015,21,2,White Rock,Customer Service,Cashier,39,F,Female,Layoff,Involuntary,2015,TERMINATED,STORES
49651,8296,12/1/2013 0:00,9/2/1994,10/9/2013,12/31/2013,19,0,Kelowna,Customer Service,Cashier,16,F,Female,Resignaton,Voluntary,2013,TERMINATED,STORES
49652,8321,12/1/2014 0:00,11/28/1994,11/24/2013,12/30/2014,20,1,Grand Forks,Customer Service,Cashier,13,F,Female,Layoff,Involuntary,2014,TERMINATED,STORES

In [3]:
null_values

EmployeeID             0
recorddate_key         0
birthdate_key          0
orighiredate_key       0
terminationdate_key    0
age                    0
length_of_service      0
city_name              0
department_name        0
job_title              0
store_name             0
gender_short           0
gender_full            0
termreason_desc        0
termtype_desc          0
STATUS_YEAR            0
STATUS                 0
BUSINESS_UNIT          0
dtype: int64

In [4]:
missing_values

EmployeeID             0
recorddate_key         0
birthdate_key          0
orighiredate_key       0
terminationdate_key    0
age                    0
length_of_service      0
city_name              0
department_name        0
job_title              0
store_name             0
gender_short           0
gender_full            0
termreason_desc        0
termtype_desc          0
STATUS_YEAR            0
STATUS                 0
BUSINESS_UNIT          0
dtype: int64

In [5]:
train_csv=trainx_csv.iloc[:,:9]
train2_csv=trainx_csv.iloc[:,9:]
train2_csv

,job_title,store_name,gender_short,gender_full,termreason_desc,termtype_desc,STATUS_YEAR,STATUS,BUSINESS_UNIT
0,CEO,35,M,Male,Not Applicable,Not Applicable,2006,ACTIVE,HEADOFFICE
1,CEO,35,M,Male,Not Applicable,Not Applicable,2007,ACTIVE,HEADOFFICE
2,CEO,35,M,Male,Not Applicable,Not Applicable,2008,ACTIVE,HEADOFFICE
3,CEO,35,M,Male,Not Applicable,Not Applicable,2009,ACTIVE,HEADOFFICE
4,CEO,35,M,Male,Not Applicable,Not Applicable,2010,ACTIVE,HEADOFFICE
...,...,...,...,...,...,...,...,...,...
49648,Dairy Person,34,M,Male,Layoff,Involuntary,2015,TERMINATED,STORES
49649,Cashier,44,F,Female,Resignaton,Voluntary,2013,TERMINATED,STORES
49650,Cashier,39,F,Female,Layoff,Involuntary,2015,TERMINATED,STORES
49651,Cashier,16,F,Female,Resignaton,Voluntary,2013,TERMINATED,STORES
49652,Cashier,13,F,Female,Layoff,Involuntary,2014,TERMINATED,STORES

In [6]:
count_dept=train_csv['department_name'].nunique()
count_dept_names=train_csv['department_name'].value_counts()
count_dept_names

Meats                     10269
Dairy                      8599
Produce                    8515
Bakery                     8381
Customer Service           7122
Processed Foods            5911
Store Management            271
Executive                   100
Recruitment                  72
HR Technology                64
Accounting                   59
Employee Records             44
Accounts Receiveable         39
Labor Relations              34
Accounts Payable             34
Training                     30
Compensation                 24
Audit                        24
Investment                   24
Information Technology       20
Legal                        17
Name: department_name, dtype: int64

In [7]:
count_city=train_csv['city_name'].nunique()
count_city_name=train_csv['city_name'].value_counts()
count_city_name

Vancouver           11211
Victoria             4885
Nanaimo              3876
New Westminster      3211
Kelowna              2513
Burnaby              2067
Kamloops             2061
Prince George        2048
Cranbrook            1785
Surrey               1560
Richmond             1401
Terrace              1228
Chilliwack           1167
Trail                 925
Langley               901
Vernon                898
Squamish              806
Quesnel               703
Abbotsford            681
North Vancouver       648
Fort St John          621
Williams Lake         617
West Vancouver        613
Port Coquitlam        545
Aldergrove            520
Fort Nelson           322
Nelson                317
New Westminister      254
Grand Forks           236
White Rock            231
Haney                 182
Princeton             136
Dawson Creek          129
Bella Bella           126
Ocean Falls            65
Pitt Meadows           57
Cortes Island          43
Valemount              37
Dease Lake             18
Blue River              9
Name: city_name, dtype: int64

In [8]:
count_job=train2_csv['job_title'].nunique()
count_job_name=train2_csv['job_title'].value_counts()
count_job_name

Meat Cutter                        9984
Dairy Person                       8590
Produce Clerk                      8237
Baker                              8096
Cashier                            6816
Shelf Stocker                      5622
Customer Service Manager            306
Processed Foods Manager             289
Bakery Manager                      285
Meats Manager                       285
Produce Manager                     278
Store Manager                       271
Recruiter                            62
HRIS Analyst                         55
Accounting Clerk                     50
Benefits Admin                       35
Labor Relations Analyst              30
Accounts Receiveable Clerk           30
Trainer                              26
Accounts Payable Clerk               25
Auditor                              20
Systems Analyst                      20
Investment Analyst                   20
Compensation Analyst                 20
Corporate Lawyer                     17
CEO                                  10
Exec Assistant, VP Stores            10
Legal Counsel                        10
VP Stores                            10
VP Human Resources                   10
VP Finance                           10
Director, Recruitment                10
Exec Assistant, Finance              10
Exec Assistant, Human Resources      10
CHief Information Officer            10
Exec Assistant, Legal Counsel        10
Director, Accounts Payable            9
Director, Accounts Receivable         9
Director, Employee Records            9
Director, HR Technology               9
Dairy Manager                         9
Director, Accounting                  9
Director, Investments                 4
Director, Labor Relations             4
Director, Compensation                4
Director, Audit                       4
Director, Training                    4
Name: job_title, dtype: int64

In [9]:
count_status=train2_csv['STATUS'].nunique()
count_status_name=train2_csv['STATUS'].value_counts()
count_status_name

ACTIVE        48168
TERMINATED     1485
Name: STATUS, dtype: int64

In [10]:
count_unit=train2_csv['BUSINESS_UNIT'].nunique()
count_unit_name=train2_csv['BUSINESS_UNIT'].value_counts()
count_unit_name

STORES        49068
HEADOFFICE      585
Name: BUSINESS_UNIT, dtype: int64

In [11]:
Mapping={}
unique_departments = train_csv['department_name'].unique()
for i,ch in enumerate(unique_departments):
    Mapping[ch]=i

train_csv['dept'] = train_csv['department_name'].map(Mapping)

In [12]:
Mapping={}
unique_city = train_csv['city_name'].unique()
for i,ch in enumerate(unique_city):
    Mapping[ch]=i
train_csv['city']=train_csv['city_name'].map(Mapping)
train_csv

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,dept,city
0,1318,12/31/2006 0:00,1/3/1954,8/28/1989,1/1/1900,52,17,Vancouver,Executive,0,0
1,1318,12/31/2007 0:00,1/3/1954,8/28/1989,1/1/1900,53,18,Vancouver,Executive,0,0
2,1318,12/31/2008 0:00,1/3/1954,8/28/1989,1/1/1900,54,19,Vancouver,Executive,0,0
3,1318,12/31/2009 0:00,1/3/1954,8/28/1989,1/1/1900,55,20,Vancouver,Executive,0,0
4,1318,12/31/2010 0:00,1/3/1954,8/28/1989,1/1/1900,56,21,Vancouver,Executive,0,0
...,...,...,...,...,...,...,...,...,...,...,...
49648,8258,12/1/2015 0:00,5/28/1994,8/19/2013,12/30/2015,21,2,Valemount,Dairy,18,34
49649,8264,8/1/2013 0:00,6/13/1994,8/27/2013,8/30/2013,19,0,Vancouver,Customer Service,20,0
49650,8279,12/1/2015 0:00,7/18/1994,9/15/2013,12/30/2015,21,2,White Rock,Customer Service,20,30
49651,8296,12/1/2013 0:00,9/2/1994,10/9/2013,12/31/2013,19,0,Kelowna,Customer Service,20,4
49652,8321,12/1/2014 0:00,11/28/1994,11/24/2013,12/30/2014,20,1,Grand Forks,Customer Service,20,24

In [13]:
train_csv=train_csv.drop(['recorddate_key','birthdate_key','orighiredate_key','terminationdate_key','city_name','department_name'],axis=1)
train_csv

       EmployeeID  age  length_of_service  dept  city
0            1318   52                 17     0     0
1            1318   53                 18     0     0
2            1318   54                 19     0     0
3            1318   55                 20     0     0
4            1318   56                 21     0     0
...           ...  ...                ...   ...   ...
49648        8258   21                  2    18    34
49649        8264   19                  0    20     0
49650        8279   21                  2    20    30
49651        8296   19                  0    20     4
49652        8321   20                  1    20    24

[49653 rows x 5 columns]

In [14]:
Mapping={}
unique_values=train2_csv['job_title'].unique()
for i, ch in enumerate(unique_values):
    Mapping[ch]=i
train2_csv['job']=train2_csv['job_title'].map(Mapping)

In [15]:
Mapping={}
unique_values=train2_csv['STATUS'].unique()
for i, ch in enumerate(unique_values):
    Mapping[ch]=i
train2_csv['attrition']=train2_csv['STATUS'].map(Mapping)

In [16]:
Mapping={}
unique_values=train2_csv['BUSINESS_UNIT'].unique()
for i, ch in enumerate(unique_values):
    Mapping[ch]=i
train2_csv['Business']=train2_csv['BUSINESS_UNIT'].map(Mapping)

In [17]:
Mapping={}
unique_values=train2_csv['termreason_desc'].unique()
for i, ch in enumerate(unique_values):
    Mapping[ch]=i
train2_csv['Reason']=train2_csv['termreason_desc'].map(Mapping)

In [18]:
Mapping={}
unique_values=train2_csv['termtype_desc'].unique()
for i, ch in enumerate(unique_values):
    Mapping[ch]=i
train2_csv['Type']=train2_csv['termtype_desc'].map(Mapping)

In [19]:
train2_csv=train2_csv.drop(['job_title','gender_short','gender_full','termreason_desc','termtype_desc','termtype_desc','STATUS','BUSINESS_UNIT'],axis=1)
train2_csv=train2_csv.loc[:,['store_name','STATUS_YEAR','job','Business','Reason','Type','attrition']]

In [20]:
merge_df=pd.merge(train_csv,train2_csv,left_index=True,right_index=True)
merge_df=merge_df.astype(np.float64)
merge_df

,EmployeeID,age,length_of_service,dept,city,store_name,STATUS_YEAR,job,Business,Reason,Type,attrition
0,1318.0,52.0,17.0,0.0,0.0,35.0,2006.0,0.0,0.0,0.0,0.0,0.0
1,1318.0,53.0,18.0,0.0,0.0,35.0,2007.0,0.0,0.0,0.0,0.0,0.0
2,1318.0,54.0,19.0,0.0,0.0,35.0,2008.0,0.0,0.0,0.0,0.0,0.0
3,1318.0,55.0,20.0,0.0,0.0,35.0,2009.0,0.0,0.0,0.0,0.0,0.0
4,1318.0,56.0,21.0,0.0,0.0,35.0,2010.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49648,8258.0,21.0,2.0,18.0,34.0,34.0,2015.0,27.0,1.0,3.0,2.0,1.0
49649,8264.0,19.0,0.0,20.0,0.0,44.0,2013.0,46.0,1.0,2.0,1.0,1.0
49650,8279.0,21.0,2.0,20.0,30.0,39.0,2015.0,46.0,1.0,3.0,2.0,1.0
49651,8296.0,19.0,0.0,20.0,4.0,16.0,2013.0,46.0,1.0,2.0,1.0,1.0
49652,8321.0,20.0,1.0,20.0,24.0,13.0,2014.0,46.0,1.0,3.0,2.0,1.0

In [21]:
attributes=['age','length_of_service','dept','city','store_name','job','Business','Reason','Type']
x=merge_df[attributes].values
y=merge_df['attrition'].values
f2,z=f_regression(x,y,center=True,force_finite=True)
results=pd.DataFrame({'Attribute': attributes, 'F-Statistic': f2, 'P-Value':z})

In [ ]:
k_best=SelectKBest(score_func=f_regression,k=6)
x_new=k_best.fit_transform(x,y)
indices=k_best.get_support(indices=True)
S_attributes=[attributes[i] for i in indices]
features=pd.DataFrame(x_new,columns=S_attributes)
features

        age  dept  city  Business  Reason  Type
0      52.0   0.0   0.0       0.0     0.0   0.0
1      53.0   0.0   0.0       0.0     0.0   0.0
2      54.0   0.0   0.0       0.0     0.0   0.0
3      55.0   0.0   0.0       0.0     0.0   0.0
4      56.0   0.0   0.0       0.0     0.0   0.0
...     ...   ...   ...       ...     ...   ...
49648  21.0  18.0  34.0       1.0     3.0   2.0
49649  19.0  20.0   0.0       1.0     2.0   1.0
49650  21.0  20.0  30.0       1.0     3.0   2.0
49651  19.0  20.0   4.0       1.0     2.0   1.0
49652  20.0  20.0  24.0       1.0     3.0   2.0

[49653 rows x 6 columns]

In [22]:
new_attributes=['age','dept','city','Business','Reason','Type']
Selected_attributes=merge_df[new_attributes].values

In [24]:
acc=accuracy_score(y_test,y_pred)
acc

1.0

In [23]:
X_train,X_test,y_train,y_test=train_test_split(Selected_attributes,y,test_size=0.30,random_state=42)
Model=LogisticRegression()
Model.fit(X_train, y_train)
y_pred = Model.predict(X_test)
y_pred_np=np.array(y_pred)
y_pred_pd=pd.DataFrame(y_pred)

In [27]:
svm_classifier = SVC(kernel='rbf', C=1.0, gamma='scale')
svm_classifier.fit(X_train, y_train)
predictions = svm_classifier.predict(X_test)

In [28]:
acc=accuracy_score(y_test,predictions)
acc

1.0

In [29]:
attrition=y_pred_np
file_n='Sample_Submission.csv'
with open(file_n,'w',newline='') as csvfile:
  csv_w=csv.writer(csvfile)
  csv_w.writerow(['attrition'])
  for Attrition in attrition:
    csv_w.writerow([Attrition])

In [30]:
y_pred_pd

         0
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
...    ...
14891  0.0
14892  0.0
14893  0.0
14894  0.0
14895  0.0

[14896 rows x 1 columns]